# Problem:
# 

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?


''' BRUTE FORCE '''

# Author: Jonathan Lebron (Github: jonathanlebron, Twitter: @_jlebron)
# Date: 11/8/2013

def getNthTriangularNumber(n):
    out = 0
    for i in range(1,n+1):
        out += i
        
    return out

def getNumFactors(n):
    factors = 2
    m = int(math.sqrt(n))+1
    
    for i in range(2, m):
        if n%i == 0:
            factors += 2

    return factors

n = 1
currTriNum = 1
numFactors = len(getFactors(currTriNum))

while numFactors < 500:
    n += 1
    currTriNum += n
    numFactors = getNumFactors(currTriNum)
    
print currTriNum
